// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: common/v1/types.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HealthStatus represents the health state of a component.
type HealthStatus int32

const (
	HealthStatus_HEALTH_STATUS_UNSPECIFIED HealthStatus = 0
	HealthStatus_HEALTH_STATUS_HEALTHY     HealthStatus = 1
	HealthStatus_HEALTH_STATUS_DEGRADED    HealthStatus = 2
	HealthStatus_HEALTH_STATUS_UNHEALTHY   HealthStatus = 3
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "HEALTH_STATUS_UNSPECIFIED",
		1: "HEALTH_STATUS_HEALTHY",
		2: "HEALTH_STATUS_DEGRADED",
		3: "HEALTH_STATUS_UNHEALTHY",
	}
	HealthStatus_value = map[string]int32{
		"HEALTH_STATUS_UNSPECIFIED": 0,
		"HEALTH_STATUS_HEALTHY":     1,
		"HEALTH_STATUS_DEGRADED":    2,
		"HEALTH_STATUS_UNHEALTHY":   3,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_types_proto_enumTypes[0].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_common_v1_types_proto_enumTypes[0]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_types_proto_rawDescGZIP(), []int{0}
}

// CertificateInfo represents a full certificate with all its details.
type CertificateInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CommonName        string                 `protobuf:"bytes,2,opt,name=common_name,json=commonName,proto3" json:"common_name,omitempty"`
	Sans              []string               `protobuf:"bytes,3,rep,name=sans,proto3" json:"sans,omitempty"`
	SerialNumber      string                 `protobuf:"bytes,4,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	IssuerDn          string                 `protobuf:"bytes,5,opt,name=issuer_dn,json=issuerDn,proto3" json:"issuer_dn,omitempty"`
	SubjectDn         string                 `protobuf:"bytes,6,opt,name=subject_dn,json=subjectDn,proto3" json:"subject_dn,omitempty"`
	NotBefore         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter          *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	KeyType           string                 `protobuf:"bytes,9,opt,name=key_type,json=keyType,proto3" json:"key_type,omitempty"` // RSA, ECDSA, Ed25519
	KeySize           int32                  `protobuf:"varint,10,opt,name=key_size,json=keySize,proto3" json:"key_size,omitempty"`
	FingerprintSha256 string                 `protobuf:"bytes,11,opt,name=fingerprint_sha256,json=fingerprintSha256,proto3" json:"fingerprint_sha256,omitempty"`
	CertificatePem    []byte                 `protobuf:"bytes,12,opt,name=certificate_pem,json=certificatePem,proto3" json:"certificate_pem,omitempty"`
	ChainPem          []byte                 `protobuf:"bytes,13,opt,name=chain_pem,json=chainPem,proto3" json:"chain_pem,omitempty"`
	PrivateKeyPem     []byte                 `protobuf:"bytes,14,opt,name=private_key_pem,json=privateKeyPem,proto3" json:"private_key_pem,omitempty"` // Only populated when issuing/renewing
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CertificateInfo) Reset() {
	*x = CertificateInfo{}
	mi := &file_common_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateInfo) ProtoMessage() {}

func (x *CertificateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateInfo.ProtoReflect.Descriptor instead.
func (*CertificateInfo) Descriptor() ([]byte, []int) {
	return file_common_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *CertificateInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CertificateInfo) GetCommonName() string {
	if x != nil {
		return x.CommonName
	}
	return ""
}

func (x *CertificateInfo) GetSans() []string {
	if x != nil {
		return x.Sans
	}
	return nil
}

func (x *CertificateInfo) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *CertificateInfo) GetIssuerDn() string {
	if x != nil {
		return x.IssuerDn
	}
	return ""
}

func (x *CertificateInfo) GetSubjectDn() string {
	if x != nil {
		return x.SubjectDn
	}
	return ""
}

func (x *CertificateInfo) GetNotBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.NotBefore
	}
	return nil
}

func (x *CertificateInfo) GetNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

func (x *CertificateInfo) GetKeyType() string {
	if x != nil {
		return x.KeyType
	}
	return ""
}

func (x *CertificateInfo) GetKeySize() int32 {
	if x != nil {
		return x.KeySize
	}
	return 0
}

func (x *CertificateInfo) GetFingerprintSha256() string {
	if x != nil {
		return x.FingerprintSha256
	}
	return ""
}

func (x *CertificateInfo) GetCertificatePem() []byte {
	if x != nil {
		return x.CertificatePem
	}
	return nil
}

func (x *CertificateInfo) GetChainPem() []byte {
	if x != nil {
		return x.ChainPem
	}
	return nil
}

func (x *CertificateInfo) GetPrivateKeyPem() []byte {
	if x != nil {
		return x.PrivateKeyPem
	}
	return nil
}

// CAAuthorityInfo contains information about a Certificate Authority.
type CAAuthorityInfo struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Id                      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                    string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SubjectDn               string                 `protobuf:"bytes,3,opt,name=subject_dn,json=subjectDn,proto3" json:"subject_dn,omitempty"`
	IssuerDn                string                 `protobuf:"bytes,4,opt,name=issuer_dn,json=issuerDn,proto3" json:"issuer_dn,omitempty"`
	NotBefore               *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter                *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	DaysRemaining           int32                  `protobuf:"varint,7,opt,name=days_remaining,json=daysRemaining,proto3" json:"days_remaining,omitempty"`
	FingerprintSha256       string                 `protobuf:"bytes,8,opt,name=fingerprint_sha256,json=fingerprintSha256,proto3" json:"fingerprint_sha256,omitempty"`
	CaType                  string                 `protobuf:"bytes,9,opt,name=ca_type,json=caType,proto3" json:"ca_type,omitempty"` // ROOT, INTERMEDIATE, ISSUING
	CrlUrl                  string                 `protobuf:"bytes,10,opt,name=crl_url,json=crlUrl,proto3" json:"crl_url,omitempty"`
	OcspUrl                 string                 `protobuf:"bytes,11,opt,name=ocsp_url,json=ocspUrl,proto3" json:"ocsp_url,omitempty"`
	IsCrlFresh              bool                   `protobuf:"varint,12,opt,name=is_crl_fresh,json=isCrlFresh,proto3" json:"is_crl_fresh,omitempty"`
	IsOcspResponsive        bool                   `protobuf:"varint,13,opt,name=is_ocsp_responsive,json=isOcspResponsive,proto3" json:"is_ocsp_responsive,omitempty"`
	CertificatesIssuedCount int64                  `protobuf:"varint,14,opt,name=certificates_issued_count,json=certificatesIssuedCount,proto3" json:"certificates_issued_count,omitempty"`
	CertificatePem          []byte                 `protobuf:"bytes,15,opt,name=certificate_pem,json=certificatePem,proto3" json:"certificate_pem,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *CAAuthorityInfo) Reset() {
	*x = CAAuthorityInfo{}
	mi := &file_common_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAAuthorityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAAuthorityInfo) ProtoMessage() {}

func (x *CAAuthorityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAAuthorityInfo.ProtoReflect.Descriptor instead.
func (*CAAuthorityInfo) Descriptor() ([]byte, []int) {
	return file_common_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *CAAuthorityInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CAAuthorityInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CAAuthorityInfo) GetSubjectDn() string {
	if x != nil {
		return x.SubjectDn
	}
	return ""
}

func (x *CAAuthorityInfo) GetIssuerDn() string {
	if x != nil {
		return x.IssuerDn
	}
	return ""
}

func (x *CAAuthorityInfo) GetNotBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.NotBefore
	}
	return nil
}

func (x *CAAuthorityInfo) GetNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

func (x *CAAuthorityInfo) GetDaysRemaining() int32 {
	if x != nil {
		return x.DaysRemaining
	}
	return 0
}

func (x *CAAuthorityInfo) GetFingerprintSha256() string {
	if x != nil {
		return x.FingerprintSha256
	}
	return ""
}

func (x *CAAuthorityInfo) GetCaType() string {
	if x != nil {
		return x.CaType
	}
	return ""
}

func (x *CAAuthorityInfo) GetCrlUrl() string {
	if x != nil {
		return x.CrlUrl
	}
	return ""
}

func (x *CAAuthorityInfo) GetOcspUrl() string {
	if x != nil {
		return x.OcspUrl
	}
	return ""
}

func (x *CAAuthorityInfo) GetIsCrlFresh() bool {
	if x != nil {
		return x.IsCrlFresh
	}
	return false
}

func (x *CAAuthorityInfo) GetIsOcspResponsive() bool {
	if x != nil {
		return x.IsOcspResponsive
	}
	return false
}

func (x *CAAuthorityInfo) GetCertificatesIssuedCount() int64 {
	if x != nil {
		return x.CertificatesIssuedCount
	}
	return 0
}

func (x *CAAuthorityInfo) GetCertificatePem() []byte {
	if x != nil {
		return x.CertificatePem
	}
	return nil
}

// ProviderCapabilities describes what a gateway plugin supports.
type ProviderCapabilities struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ProviderName        string                 `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	ProviderVersion     string                 `protobuf:"bytes,2,opt,name=provider_version,json=providerVersion,proto3" json:"provider_version,omitempty"`
	ProviderType        string                 `protobuf:"bytes,3,opt,name=provider_type,json=providerType,proto3" json:"provider_type,omitempty"` // acme, vault, selfsigned, gcp_cas, etc.
	SupportsWildcard    bool                   `protobuf:"varint,4,opt,name=supports_wildcard,json=supportsWildcard,proto3" json:"supports_wildcard,omitempty"`
	SupportsMultiDomain bool                   `protobuf:"varint,5,opt,name=supports_multi_domain,json=supportsMultiDomain,proto3" json:"supports_multi_domain,omitempty"`
	SupportedKeyTypes   []string               `protobuf:"bytes,6,rep,name=supported_key_types,json=supportedKeyTypes,proto3" json:"supported_key_types,omitempty"`     // RSA, ECDSA, Ed25519
	SupportedChallenges []string               `protobuf:"bytes,7,rep,name=supported_challenges,json=supportedChallenges,proto3" json:"supported_challenges,omitempty"` // http-01, dns-01, tls-alpn-01
	ValidationLevels    []string               `protobuf:"bytes,8,rep,name=validation_levels,json=validationLevels,proto3" json:"validation_levels,omitempty"`          // DV, OV, EV
	SupportsRevocation  bool                   `protobuf:"varint,9,opt,name=supports_revocation,json=supportsRevocation,proto3" json:"supports_revocation,omitempty"`
	SupportsCaInfo      bool                   `protobuf:"varint,10,opt,name=supports_ca_info,json=supportsCaInfo,proto3" json:"supports_ca_info,omitempty"` // Can report CA certificate details
	Description         string                 `protobuf:"bytes,11,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ProviderCapabilities) Reset() {
	*x = ProviderCapabilities{}
	mi := &file_common_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderCapabilities) ProtoMessage() {}

func (x *ProviderCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderCapabilities.ProtoReflect.Descriptor instead.
func (*ProviderCapabilities) Descriptor() ([]byte, []int) {
	return file_common_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *ProviderCapabilities) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *ProviderCapabilities) GetProviderVersion() string {
	if x != nil {
		return x.ProviderVersion
	}
	return ""
}

func (x *ProviderCapabilities) GetProviderType() string {
	if x != nil {
		return x.ProviderType
	}
	return ""
}

func (x *ProviderCapabilities) GetSupportsWildcard() bool {
	if x != nil {
		return x.SupportsWildcard
	}
	return false
}

func (x *ProviderCapabilities) GetSupportsMultiDomain() bool {
	if x != nil {
		return x.SupportsMultiDomain
	}
	return false
}

func (x *ProviderCapabilities) GetSupportedKeyTypes() []string {
	if x != nil {
		return x.SupportedKeyTypes
	}
	return nil
}

func (x *ProviderCapabilities) GetSupportedChallenges() []string {
	if x != nil {
		return x.SupportedChallenges
	}
	return nil
}

func (x *ProviderCapabilities) GetValidationLevels() []string {
	if x != nil {
		return x.ValidationLevels
	}
	return nil
}

func (x *ProviderCapabilities) GetSupportsRevocation() bool {
	if x != nil {
		return x.SupportsRevocation
	}
	return false
}

func (x *ProviderCapabilities) GetSupportsCaInfo() bool {
	if x != nil {
		return x.SupportsCaInfo
	}
	return false
}

func (x *ProviderCapabilities) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_common_v1_types_proto protoreflect.FileDescriptor

const file_common_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x15common/v1/types.proto\x12\x13certpilot.common.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfe\x03\n" +
	"\x0fCertificateInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcommon_name\x18\x02 \x01(\tR\n" +
	"commonName\x12\x12\n" +
	"\x04sans\x18\x03 \x03(\tR\x04sans\x12#\n" +
	"\rserial_number\x18\x04 \x01(\tR\fserialNumber\x12\x1b\n" +
	"\tissuer_dn\x18\x05 \x01(\tR\bissuerDn\x12\x1d\n" +
	"\n" +
	"subject_dn\x18\x06 \x01(\tR\tsubjectDn\x129\n" +
	"\n" +
	"not_before\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tnotBefore\x127\n" +
	"\tnot_after\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\bnotAfter\x12\x19\n" +
	"\bkey_type\x18\t \x01(\tR\akeyType\x12\x19\n" +
	"\bkey_size\x18\n" +
	" \x01(\x05R\akeySize\x12-\n" +
	"\x12fingerprint_sha256\x18\v \x01(\tR\x11fingerprintSha256\x12'\n" +
	"\x0fcertificate_pem\x18\f \x01(\fR\x0ecertificatePem\x12\x1b\n" +
	"\tchain_pem\x18\r \x01(\fR\bchainPem\x12&\n" +
	"\x0fprivate_key_pem\x18\x0e \x01(\fR\rprivateKeyPem\"\xbd\x04\n" +
	"\x0fCAAuthorityInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"subject_dn\x18\x03 \x01(\tR\tsubjectDn\x12\x1b\n" +
	"\tissuer_dn\x18\x04 \x01(\tR\bissuerDn\x129\n" +
	"\n" +
	"not_before\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tnotBefore\x127\n" +
	"\tnot_after\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bnotAfter\x12%\n" +
	"\x0edays_remaining\x18\a \x01(\x05R\rdaysRemaining\x12-\n" +
	"\x12fingerprint_sha256\x18\b \x01(\tR\x11fingerprintSha256\x12\x17\n" +
	"\aca_type\x18\t \x01(\tR\x06caType\x12\x17\n" +
	"\acrl_url\x18\n" +
	" \x01(\tR\x06crlUrl\x12\x19\n" +
	"\bocsp_url\x18\v \x01(\tR\aocspUrl\x12 \n" +
	"\fis_crl_fresh\x18\f \x01(\bR\n" +
	"isCrlFresh\x12,\n" +
	"\x12is_ocsp_responsive\x18\r \x01(\bR\x10isOcspResponsive\x12:\n" +
	"\x19certificates_issued_count\x18\x0e \x01(\x03R\x17certificatesIssuedCount\x12'\n" +
	"\x0fcertificate_pem\x18\x0f \x01(\fR\x0ecertificatePem\"\xf9\x03\n" +
	"\x14ProviderCapabilities\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\x12)\n" +
	"\x10provider_version\x18\x02 \x01(\tR\x0fproviderVersion\x12#\n" +
	"\rprovider_type\x18\x03 \x01(\tR\fproviderType\x12+\n" +
	"\x11supports_wildcard\x18\x04 \x01(\bR\x10supportsWildcard\x122\n" +
	"\x15supports_multi_domain\x18\x05 \x01(\bR\x13supportsMultiDomain\x12.\n" +
	"\x13supported_key_types\x18\x06 \x03(\tR\x11supportedKeyTypes\x121\n" +
	"\x14supported_challenges\x18\a \x03(\tR\x13supportedChallenges\x12+\n" +
	"\x11validation_levels\x18\b \x03(\tR\x10validationLevels\x12/\n" +
	"\x13supports_revocation\x18\t \x01(\bR\x12supportsRevocation\x12(\n" +
	"\x10supports_ca_info\x18\n" +
	" \x01(\bR\x0esupportsCaInfo\x12 \n" +
	"\vdescription\x18\v \x01(\tR\vdescription*\x81\x01\n" +
	"\fHealthStatus\x12\x1d\n" +
	"\x19HEALTH_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15HEALTH_STATUS_HEALTHY\x10\x01\x12\x1a\n" +
	"\x16HEALTH_STATUS_DEGRADED\x10\x02\x12\x1b\n" +
	"\x17HEALTH_STATUS_UNHEALTHY\x10\x03B\xcd\x01\n" +
	"\x17com.certpilot.common.v1B\n" +
	"TypesProtoP\x01Z8github.com/certpilot/certpilot/pkg/pb/common/v1;commonv1\xa2\x02\x03CCX\xaa\x02\x13Certpilot.Common.V1\xca\x02\x13Certpilot\\Common\\V1\xe2\x02\x1fCertpilot\\Common\\V1\\GPBMetadata\xea\x02\x15Certpilot::Common::V1b\x06proto3"

var (
	file_common_v1_types_proto_rawDescOnce sync.Once
	file_common_v1_types_proto_rawDescData []byte
)

func file_common_v1_types_proto_rawDescGZIP() []byte {
	file_common_v1_types_proto_rawDescOnce.Do(func() {
		file_common_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_types_proto_rawDesc), len(file_common_v1_types_proto_rawDesc)))
	})
	return file_common_v1_types_proto_rawDescData
}

var file_common_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_common_v1_types_proto_goTypes = []any{
	(HealthStatus)(0),             // 0: certpilot.common.v1.HealthStatus
	(*CertificateInfo)(nil),       // 1: certpilot.common.v1.CertificateInfo
	(*CAAuthorityInfo)(nil),       // 2: certpilot.common.v1.CAAuthorityInfo
	(*ProviderCapabilities)(nil),  // 3: certpilot.common.v1.ProviderCapabilities
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_common_v1_types_proto_depIdxs = []int32{
	4, // 0: certpilot.common.v1.CertificateInfo.not_before:type_name -> google.protobuf.Timestamp
	4, // 1: certpilot.common.v1.CertificateInfo.not_after:type_name -> google.protobuf.Timestamp
	4, // 2: certpilot.common.v1.CAAuthorityInfo.not_before:type_name -> google.protobuf.Timestamp
	4, // 3: certpilot.common.v1.CAAuthorityInfo.not_after:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_common_v1_types_proto_init() }
func file_common_v1_types_proto_init() {
	if File_common_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_types_proto_rawDesc), len(file_common_v1_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_types_proto_goTypes,
		DependencyIndexes: file_common_v1_types_proto_depIdxs,
		EnumInfos:         file_common_v1_types_proto_enumTypes,
		MessageInfos:      file_common_v1_types_proto_msgTypes,
	}.Build()
	File_common_v1_types_proto = out.File
	file_common_v1_types_proto_goTypes = nil
	file_common_v1_types_proto_depIdxs = nil
}
