// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: provider/v1/provider.proto

package providerv1

import (
	v1 "github.com/certpilot/certpilot/pkg/pb/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CertStatus int32

const (
	CertStatus_CERT_STATUS_UNSPECIFIED CertStatus = 0
	CertStatus_CERT_STATUS_VALID       CertStatus = 1
	CertStatus_CERT_STATUS_EXPIRED     CertStatus = 2
	CertStatus_CERT_STATUS_REVOKED     CertStatus = 3
	CertStatus_CERT_STATUS_PENDING     CertStatus = 4
	CertStatus_CERT_STATUS_UNKNOWN     CertStatus = 5
)

// Enum value maps for CertStatus.
var (
	CertStatus_name = map[int32]string{
		0: "CERT_STATUS_UNSPECIFIED",
		1: "CERT_STATUS_VALID",
		2: "CERT_STATUS_EXPIRED",
		3: "CERT_STATUS_REVOKED",
		4: "CERT_STATUS_PENDING",
		5: "CERT_STATUS_UNKNOWN",
	}
	CertStatus_value = map[string]int32{
		"CERT_STATUS_UNSPECIFIED": 0,
		"CERT_STATUS_VALID":       1,
		"CERT_STATUS_EXPIRED":     2,
		"CERT_STATUS_REVOKED":     3,
		"CERT_STATUS_PENDING":     4,
		"CERT_STATUS_UNKNOWN":     5,
	}
)

func (x CertStatus) Enum() *CertStatus {
	p := new(CertStatus)
	*p = x
	return p
}

func (x CertStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CertStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_provider_v1_provider_proto_enumTypes[0].Descriptor()
}

func (CertStatus) Type() protoreflect.EnumType {
	return &file_provider_v1_provider_proto_enumTypes[0]
}

func (x CertStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CertStatus.Descriptor instead.
func (CertStatus) EnumDescriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{0}
}

type IssueCertificateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CSR in PEM format. If empty, the gateway generates the key pair.
	CsrPem []byte `protobuf:"bytes,1,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`
	// Domains to include in the certificate.
	Domains []string `protobuf:"bytes,2,rep,name=domains,proto3" json:"domains,omitempty"`
	// Key type to use if generating a key pair (RSA, ECDSA, Ed25519).
	KeyType string `protobuf:"bytes,3,opt,name=key_type,json=keyType,proto3" json:"key_type,omitempty"`
	// Key size (e.g., 2048, 4096 for RSA; 256, 384 for ECDSA).
	KeySize int32 `protobuf:"varint,4,opt,name=key_size,json=keySize,proto3" json:"key_size,omitempty"`
	// Requested validity duration in days (CA may override).
	ValidityDays int32 `protobuf:"varint,5,opt,name=validity_days,json=validityDays,proto3" json:"validity_days,omitempty"`
	// Provider-specific configuration as JSON.
	ProviderConfig string `protobuf:"bytes,6,opt,name=provider_config,json=providerConfig,proto3" json:"provider_config,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IssueCertificateRequest) Reset() {
	*x = IssueCertificateRequest{}
	mi := &file_provider_v1_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueCertificateRequest) ProtoMessage() {}

func (x *IssueCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueCertificateRequest.ProtoReflect.Descriptor instead.
func (*IssueCertificateRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{0}
}

func (x *IssueCertificateRequest) GetCsrPem() []byte {
	if x != nil {
		return x.CsrPem
	}
	return nil
}

func (x *IssueCertificateRequest) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

func (x *IssueCertificateRequest) GetKeyType() string {
	if x != nil {
		return x.KeyType
	}
	return ""
}

func (x *IssueCertificateRequest) GetKeySize() int32 {
	if x != nil {
		return x.KeySize
	}
	return 0
}

func (x *IssueCertificateRequest) GetValidityDays() int32 {
	if x != nil {
		return x.ValidityDays
	}
	return 0
}

func (x *IssueCertificateRequest) GetProviderConfig() string {
	if x != nil {
		return x.ProviderConfig
	}
	return ""
}

type IssueCertificateResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Certificate *v1.CertificateInfo    `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`
	// Provider-specific certificate ID for future operations.
	ProviderCertificateId string `protobuf:"bytes,2,opt,name=provider_certificate_id,json=providerCertificateId,proto3" json:"provider_certificate_id,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *IssueCertificateResponse) Reset() {
	*x = IssueCertificateResponse{}
	mi := &file_provider_v1_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueCertificateResponse) ProtoMessage() {}

func (x *IssueCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueCertificateResponse.ProtoReflect.Descriptor instead.
func (*IssueCertificateResponse) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{1}
}

func (x *IssueCertificateResponse) GetCertificate() *v1.CertificateInfo {
	if x != nil {
		return x.Certificate
	}
	return nil
}

func (x *IssueCertificateResponse) GetProviderCertificateId() string {
	if x != nil {
		return x.ProviderCertificateId
	}
	return ""
}

type RenewCertificateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The provider-specific certificate ID from the original issuance.
	ProviderCertificateId string `protobuf:"bytes,1,opt,name=provider_certificate_id,json=providerCertificateId,proto3" json:"provider_certificate_id,omitempty"`
	// New CSR in PEM format. If empty, reuses domains from original cert.
	CsrPem []byte `protobuf:"bytes,2,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`
	// Domains (if different from original).
	Domains []string `protobuf:"bytes,3,rep,name=domains,proto3" json:"domains,omitempty"`
	// Key type override.
	KeyType string `protobuf:"bytes,4,opt,name=key_type,json=keyType,proto3" json:"key_type,omitempty"`
	KeySize int32  `protobuf:"varint,5,opt,name=key_size,json=keySize,proto3" json:"key_size,omitempty"`
	// The current certificate PEM (for providers that need it).
	CurrentCertificatePem []byte `protobuf:"bytes,6,opt,name=current_certificate_pem,json=currentCertificatePem,proto3" json:"current_certificate_pem,omitempty"`
	// Provider-specific configuration as JSON.
	ProviderConfig string `protobuf:"bytes,7,opt,name=provider_config,json=providerConfig,proto3" json:"provider_config,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RenewCertificateRequest) Reset() {
	*x = RenewCertificateRequest{}
	mi := &file_provider_v1_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewCertificateRequest) ProtoMessage() {}

func (x *RenewCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewCertificateRequest.ProtoReflect.Descriptor instead.
func (*RenewCertificateRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{2}
}

func (x *RenewCertificateRequest) GetProviderCertificateId() string {
	if x != nil {
		return x.ProviderCertificateId
	}
	return ""
}

func (x *RenewCertificateRequest) GetCsrPem() []byte {
	if x != nil {
		return x.CsrPem
	}
	return nil
}

func (x *RenewCertificateRequest) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

func (x *RenewCertificateRequest) GetKeyType() string {
	if x != nil {
		return x.KeyType
	}
	return ""
}

func (x *RenewCertificateRequest) GetKeySize() int32 {
	if x != nil {
		return x.KeySize
	}
	return 0
}

func (x *RenewCertificateRequest) GetCurrentCertificatePem() []byte {
	if x != nil {
		return x.CurrentCertificatePem
	}
	return nil
}

func (x *RenewCertificateRequest) GetProviderConfig() string {
	if x != nil {
		return x.ProviderConfig
	}
	return ""
}

type RenewCertificateResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Certificate           *v1.CertificateInfo    `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`
	ProviderCertificateId string                 `protobuf:"bytes,2,opt,name=provider_certificate_id,json=providerCertificateId,proto3" json:"provider_certificate_id,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RenewCertificateResponse) Reset() {
	*x = RenewCertificateResponse{}
	mi := &file_provider_v1_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewCertificateResponse) ProtoMessage() {}

func (x *RenewCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewCertificateResponse.ProtoReflect.Descriptor instead.
func (*RenewCertificateResponse) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{3}
}

func (x *RenewCertificateResponse) GetCertificate() *v1.CertificateInfo {
	if x != nil {
		return x.Certificate
	}
	return nil
}

func (x *RenewCertificateResponse) GetProviderCertificateId() string {
	if x != nil {
		return x.ProviderCertificateId
	}
	return ""
}

type RevokeCertificateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The certificate to revoke (PEM format).
	CertificatePem []byte `protobuf:"bytes,1,opt,name=certificate_pem,json=certificatePem,proto3" json:"certificate_pem,omitempty"`
	// Provider-specific certificate ID.
	ProviderCertificateId string `protobuf:"bytes,2,opt,name=provider_certificate_id,json=providerCertificateId,proto3" json:"provider_certificate_id,omitempty"`
	// RFC 5280 revocation reason code.
	// 0=unspecified, 1=keyCompromise, 3=affiliationChanged,
	// 4=superseded, 5=cessationOfOperation
	Reason int32 `protobuf:"varint,3,opt,name=reason,proto3" json:"reason,omitempty"`
	// Provider-specific configuration as JSON. Required: a gateway cannot
	// authenticate to the CA without the account credentials.
	ProviderConfig string `protobuf:"bytes,4,opt,name=provider_config,json=providerConfig,proto3" json:"provider_config,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RevokeCertificateRequest) Reset() {
	*x = RevokeCertificateRequest{}
	mi := &file_provider_v1_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeCertificateRequest) ProtoMessage() {}

func (x *RevokeCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeCertificateRequest.ProtoReflect.Descriptor instead.
func (*RevokeCertificateRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{4}
}

func (x *RevokeCertificateRequest) GetCertificatePem() []byte {
	if x != nil {
		return x.CertificatePem
	}
	return nil
}

func (x *RevokeCertificateRequest) GetProviderCertificateId() string {
	if x != nil {
		return x.ProviderCertificateId
	}
	return ""
}

func (x *RevokeCertificateRequest) GetReason() int32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

func (x *RevokeCertificateRequest) GetProviderConfig() string {
	if x != nil {
		return x.ProviderConfig
	}
	return ""
}

type RevokeCertificateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeCertificateResponse) Reset() {
	*x = RevokeCertificateResponse{}
	mi := &file_provider_v1_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeCertificateResponse) ProtoMessage() {}

func (x *RevokeCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeCertificateResponse.ProtoReflect.Descriptor instead.
func (*RevokeCertificateResponse) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{5}
}

func (x *RevokeCertificateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RevokeCertificateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetCertificateStatusRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ProviderCertificateId string                 `protobuf:"bytes,1,opt,name=provider_certificate_id,json=providerCertificateId,proto3" json:"provider_certificate_id,omitempty"`
	CertificatePem        []byte                 `protobuf:"bytes,2,opt,name=certificate_pem,json=certificatePem,proto3" json:"certificate_pem,omitempty"`
	// Provider-specific configuration as JSON. Needed to reach the CA for
	// renewal information and revocation status.
	ProviderConfig string `protobuf:"bytes,3,opt,name=provider_config,json=providerConfig,proto3" json:"provider_config,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetCertificateStatusRequest) Reset() {
	*x = GetCertificateStatusRequest{}
	mi := &file_provider_v1_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCertificateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCertificateStatusRequest) ProtoMessage() {}

func (x *GetCertificateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCertificateStatusRequest.ProtoReflect.Descriptor instead.
func (*GetCertificateStatusRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{6}
}

func (x *GetCertificateStatusRequest) GetProviderCertificateId() string {
	if x != nil {
		return x.ProviderCertificateId
	}
	return ""
}

func (x *GetCertificateStatusRequest) GetCertificatePem() []byte {
	if x != nil {
		return x.CertificatePem
	}
	return nil
}

func (x *GetCertificateStatusRequest) GetProviderConfig() string {
	if x != nil {
		return x.ProviderConfig
	}
	return ""
}

type GetCertificateStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Certificate status.
	Status    CertStatus             `protobuf:"varint,1,opt,name=status,proto3,enum=certpilot.provider.v1.CertStatus" json:"status,omitempty"`
	Message   string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// Renewal guidance published by the CA (RFC 9773). Absent when the CA does
	// not support ACME Renewal Information.
	RenewalWindow *RenewalWindow `protobuf:"bytes,4,opt,name=renewal_window,json=renewalWindow,proto3" json:"renewal_window,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCertificateStatusResponse) Reset() {
	*x = GetCertificateStatusResponse{}
	mi := &file_provider_v1_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCertificateStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCertificateStatusResponse) ProtoMessage() {}

func (x *GetCertificateStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCertificateStatusResponse.ProtoReflect.Descriptor instead.
func (*GetCertificateStatusResponse) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{7}
}

func (x *GetCertificateStatusResponse) GetStatus() CertStatus {
	if x != nil {
		return x.Status
	}
	return CertStatus_CERT_STATUS_UNSPECIFIED
}

func (x *GetCertificateStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetCertificateStatusResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *GetCertificateStatusResponse) GetRenewalWindow() *RenewalWindow {
	if x != nil {
		return x.RenewalWindow
	}
	return nil
}

// RenewalWindow carries the CA's own advice about when a certificate should be
// replaced, as defined by RFC 9773 (ACME Renewal Information).
//
// Honouring this is what lets a CA drain a mass-revocation event gradually
// instead of every client renewing at once, and it lets the CA move renewals
// off a window it knows is about to become invalid.
type RenewalWindow struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Start and end bound the window the CA suggests renewing within. A client
	// should pick a random time inside it rather than renewing at the start.
	Start *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	// ExplanationURL points at a human-readable reason, typically set when the
	// CA has brought a renewal window forward.
	ExplanationUrl string `protobuf:"bytes,3,opt,name=explanation_url,json=explanationUrl,proto3" json:"explanation_url,omitempty"`
	// RenewNow is true when the current time falls inside the suggested window.
	RenewNow bool `protobuf:"varint,4,opt,name=renew_now,json=renewNow,proto3" json:"renew_now,omitempty"`
	// RetryAfterSeconds is how long the CA asks clients to wait before polling
	// renewal information again.
	RetryAfterSeconds int64 `protobuf:"varint,5,opt,name=retry_after_seconds,json=retryAfterSeconds,proto3" json:"retry_after_seconds,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RenewalWindow) Reset() {
	*x = RenewalWindow{}
	mi := &file_provider_v1_provider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewalWindow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewalWindow) ProtoMessage() {}

func (x *RenewalWindow) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewalWindow.ProtoReflect.Descriptor instead.
func (*RenewalWindow) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{8}
}

func (x *RenewalWindow) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *RenewalWindow) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *RenewalWindow) GetExplanationUrl() string {
	if x != nil {
		return x.ExplanationUrl
	}
	return ""
}

func (x *RenewalWindow) GetRenewNow() bool {
	if x != nil {
		return x.RenewNow
	}
	return false
}

func (x *RenewalWindow) GetRetryAfterSeconds() int64 {
	if x != nil {
		return x.RetryAfterSeconds
	}
	return 0
}

type GetCAInfoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Provider-specific config to identify which CA to query.
	ProviderConfig string `protobuf:"bytes,1,opt,name=provider_config,json=providerConfig,proto3" json:"provider_config,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetCAInfoRequest) Reset() {
	*x = GetCAInfoRequest{}
	mi := &file_provider_v1_provider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCAInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCAInfoRequest) ProtoMessage() {}

func (x *GetCAInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCAInfoRequest.ProtoReflect.Descriptor instead.
func (*GetCAInfoRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{9}
}

func (x *GetCAInfoRequest) GetProviderConfig() string {
	if x != nil {
		return x.ProviderConfig
	}
	return ""
}

type GetCAInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of CA authorities in the chain (root → intermediate → issuing).
	CaChain       []*v1.CAAuthorityInfo `protobuf:"bytes,1,rep,name=ca_chain,json=caChain,proto3" json:"ca_chain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCAInfoResponse) Reset() {
	*x = GetCAInfoResponse{}
	mi := &file_provider_v1_provider_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCAInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCAInfoResponse) ProtoMessage() {}

func (x *GetCAInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCAInfoResponse.ProtoReflect.Descriptor instead.
func (*GetCAInfoResponse) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{10}
}

func (x *GetCAInfoResponse) GetCaChain() []*v1.CAAuthorityInfo {
	if x != nil {
		return x.CaChain
	}
	return nil
}

type GetCapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCapabilitiesRequest) Reset() {
	*x = GetCapabilitiesRequest{}
	mi := &file_provider_v1_provider_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilitiesRequest) ProtoMessage() {}

func (x *GetCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*GetCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{11}
}

type GetCapabilitiesResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Capabilities  *v1.ProviderCapabilities `protobuf:"bytes,1,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCapabilitiesResponse) Reset() {
	*x = GetCapabilitiesResponse{}
	mi := &file_provider_v1_provider_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilitiesResponse) ProtoMessage() {}

func (x *GetCapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*GetCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{12}
}

func (x *GetCapabilitiesResponse) GetCapabilities() *v1.ProviderCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_provider_v1_provider_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{13}
}

type HealthCheckResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Status  v1.HealthStatus        `protobuf:"varint,1,opt,name=status,proto3,enum=certpilot.common.v1.HealthStatus" json:"status,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Latency to the CA in milliseconds.
	LatencyMs     int64                  `protobuf:"varint,3,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	CheckedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_provider_v1_provider_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{14}
}

func (x *HealthCheckResponse) GetStatus() v1.HealthStatus {
	if x != nil {
		return x.Status
	}
	return v1.HealthStatus(0)
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthCheckResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *HealthCheckResponse) GetCheckedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckedAt
	}
	return nil
}

type ValidateConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Configuration JSON to validate.
	ConfigJson    string `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateConfigRequest) Reset() {
	*x = ValidateConfigRequest{}
	mi := &file_provider_v1_provider_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateConfigRequest) ProtoMessage() {}

func (x *ValidateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateConfigRequest.ProtoReflect.Descriptor instead.
func (*ValidateConfigRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{15}
}

func (x *ValidateConfigRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

type ValidateConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Errors        []string               `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	Warnings      []string               `protobuf:"bytes,3,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateConfigResponse) Reset() {
	*x = ValidateConfigResponse{}
	mi := &file_provider_v1_provider_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateConfigResponse) ProtoMessage() {}

func (x *ValidateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateConfigResponse.ProtoReflect.Descriptor instead.
func (*ValidateConfigResponse) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{16}
}

func (x *ValidateConfigResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateConfigResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ValidateConfigResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

var File_provider_v1_provider_proto protoreflect.FileDescriptor

const file_provider_v1_provider_proto_rawDesc = "" +
	"\n" +
	"\x1aprovider/v1/provider.proto\x12\x15certpilot.provider.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x15common/v1/types.proto\"\xd0\x01\n" +
	"\x17IssueCertificateRequest\x12\x17\n" +
	"\acsr_pem\x18\x01 \x01(\fR\x06csrPem\x12\x18\n" +
	"\adomains\x18\x02 \x03(\tR\adomains\x12\x19\n" +
	"\bkey_type\x18\x03 \x01(\tR\akeyType\x12\x19\n" +
	"\bkey_size\x18\x04 \x01(\x05R\akeySize\x12#\n" +
	"\rvalidity_days\x18\x05 \x01(\x05R\fvalidityDays\x12'\n" +
	"\x0fprovider_config\x18\x06 \x01(\tR\x0eproviderConfig\"\x9a\x01\n" +
	"\x18IssueCertificateResponse\x12F\n" +
	"\vcertificate\x18\x01 \x01(\v2$.certpilot.common.v1.CertificateInfoR\vcertificate\x126\n" +
	"\x17provider_certificate_id\x18\x02 \x01(\tR\x15providerCertificateId\"\x9b\x02\n" +
	"\x17RenewCertificateRequest\x126\n" +
	"\x17provider_certificate_id\x18\x01 \x01(\tR\x15providerCertificateId\x12\x17\n" +
	"\acsr_pem\x18\x02 \x01(\fR\x06csrPem\x12\x18\n" +
	"\adomains\x18\x03 \x03(\tR\adomains\x12\x19\n" +
	"\bkey_type\x18\x04 \x01(\tR\akeyType\x12\x19\n" +
	"\bkey_size\x18\x05 \x01(\x05R\akeySize\x126\n" +
	"\x17current_certificate_pem\x18\x06 \x01(\fR\x15currentCertificatePem\x12'\n" +
	"\x0fprovider_config\x18\a \x01(\tR\x0eproviderConfig\"\x9a\x01\n" +
	"\x18RenewCertificateResponse\x12F\n" +
	"\vcertificate\x18\x01 \x01(\v2$.certpilot.common.v1.CertificateInfoR\vcertificate\x126\n" +
	"\x17provider_certificate_id\x18\x02 \x01(\tR\x15providerCertificateId\"\xbc\x01\n" +
	"\x18RevokeCertificateRequest\x12'\n" +
	"\x0fcertificate_pem\x18\x01 \x01(\fR\x0ecertificatePem\x126\n" +
	"\x17provider_certificate_id\x18\x02 \x01(\tR\x15providerCertificateId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\x05R\x06reason\x12'\n" +
	"\x0fprovider_config\x18\x04 \x01(\tR\x0eproviderConfig\"O\n" +
	"\x19RevokeCertificateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa7\x01\n" +
	"\x1bGetCertificateStatusRequest\x126\n" +
	"\x17provider_certificate_id\x18\x01 \x01(\tR\x15providerCertificateId\x12'\n" +
	"\x0fcertificate_pem\x18\x02 \x01(\fR\x0ecertificatePem\x12'\n" +
	"\x0fprovider_config\x18\x03 \x01(\tR\x0eproviderConfig\"\xfb\x01\n" +
	"\x1cGetCertificateStatusResponse\x129\n" +
	"\x06status\x18\x01 \x01(\x0e2!.certpilot.provider.v1.CertStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12K\n" +
	"\x0erenewal_window\x18\x04 \x01(\v2$.certpilot.provider.v1.RenewalWindowR\rrenewalWindow\"\xe5\x01\n" +
	"\rRenewalWindow\x120\n" +
	"\x05start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\x12'\n" +
	"\x0fexplanation_url\x18\x03 \x01(\tR\x0eexplanationUrl\x12\x1b\n" +
	"\trenew_now\x18\x04 \x01(\bR\brenewNow\x12.\n" +
	"\x13retry_after_seconds\x18\x05 \x01(\x03R\x11retryAfterSeconds\";\n" +
	"\x10GetCAInfoRequest\x12'\n" +
	"\x0fprovider_config\x18\x01 \x01(\tR\x0eproviderConfig\"T\n" +
	"\x11GetCAInfoResponse\x12?\n" +
	"\bca_chain\x18\x01 \x03(\v2$.certpilot.common.v1.CAAuthorityInfoR\acaChain\"\x18\n" +
	"\x16GetCapabilitiesRequest\"h\n" +
	"\x17GetCapabilitiesResponse\x12M\n" +
	"\fcapabilities\x18\x01 \x01(\v2).certpilot.common.v1.ProviderCapabilitiesR\fcapabilities\"\x14\n" +
	"\x12HealthCheckRequest\"\xc4\x01\n" +
	"\x13HealthCheckResponse\x129\n" +
	"\x06status\x18\x01 \x01(\x0e2!.certpilot.common.v1.HealthStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x03 \x01(\x03R\tlatencyMs\x129\n" +
	"\n" +
	"checked_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcheckedAt\"8\n" +
	"\x15ValidateConfigRequest\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\tR\n" +
	"configJson\"b\n" +
	"\x16ValidateConfigResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x16\n" +
	"\x06errors\x18\x02 \x03(\tR\x06errors\x12\x1a\n" +
	"\bwarnings\x18\x03 \x03(\tR\bwarnings*\xa4\x01\n" +
	"\n" +
	"CertStatus\x12\x1b\n" +
	"\x17CERT_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11CERT_STATUS_VALID\x10\x01\x12\x17\n" +
	"\x13CERT_STATUS_EXPIRED\x10\x02\x12\x17\n" +
	"\x13CERT_STATUS_REVOKED\x10\x03\x12\x17\n" +
	"\x13CERT_STATUS_PENDING\x10\x04\x12\x17\n" +
	"\x13CERT_STATUS_UNKNOWN\x10\x052\xa6\a\n" +
	"\x1aCertificateProviderService\x12s\n" +
	"\x10IssueCertificate\x12..certpilot.provider.v1.IssueCertificateRequest\x1a/.certpilot.provider.v1.IssueCertificateResponse\x12s\n" +
	"\x10RenewCertificate\x12..certpilot.provider.v1.RenewCertificateRequest\x1a/.certpilot.provider.v1.RenewCertificateResponse\x12v\n" +
	"\x11RevokeCertificate\x12/.certpilot.provider.v1.RevokeCertificateRequest\x1a0.certpilot.provider.v1.RevokeCertificateResponse\x12\x7f\n" +
	"\x14GetCertificateStatus\x122.certpilot.provider.v1.GetCertificateStatusRequest\x1a3.certpilot.provider.v1.GetCertificateStatusResponse\x12^\n" +
	"\tGetCAInfo\x12'.certpilot.provider.v1.GetCAInfoRequest\x1a(.certpilot.provider.v1.GetCAInfoResponse\x12p\n" +
	"\x0fGetCapabilities\x12-.certpilot.provider.v1.GetCapabilitiesRequest\x1a..certpilot.provider.v1.GetCapabilitiesResponse\x12d\n" +
	"\vHealthCheck\x12).certpilot.provider.v1.HealthCheckRequest\x1a*.certpilot.provider.v1.HealthCheckResponse\x12m\n" +
	"\x0eValidateConfig\x12,.certpilot.provider.v1.ValidateConfigRequest\x1a-.certpilot.provider.v1.ValidateConfigResponseB\xde\x01\n" +
	"\x19com.certpilot.provider.v1B\rProviderProtoP\x01Z<github.com/certpilot/certpilot/pkg/pb/provider/v1;providerv1\xa2\x02\x03CPX\xaa\x02\x15Certpilot.Provider.V1\xca\x02\x15Certpilot\\Provider\\V1\xe2\x02!Certpilot\\Provider\\V1\\GPBMetadata\xea\x02\x17Certpilot::Provider::V1b\x06proto3"

var (
	file_provider_v1_provider_proto_rawDescOnce sync.Once
	file_provider_v1_provider_proto_rawDescData []byte
)

func file_provider_v1_provider_proto_rawDescGZIP() []byte {
	file_provider_v1_provider_proto_rawDescOnce.Do(func() {
		file_provider_v1_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_provider_v1_provider_proto_rawDesc), len(file_provider_v1_provider_proto_rawDesc)))
	})
	return file_provider_v1_provider_proto_rawDescData
}

var file_provider_v1_provider_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_provider_v1_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_provider_v1_provider_proto_goTypes = []any{
	(CertStatus)(0),                      // 0: certpilot.provider.v1.CertStatus
	(*IssueCertificateRequest)(nil),      // 1: certpilot.provider.v1.IssueCertificateRequest
	(*IssueCertificateResponse)(nil),     // 2: certpilot.provider.v1.IssueCertificateResponse
	(*RenewCertificateRequest)(nil),      // 3: certpilot.provider.v1.RenewCertificateRequest
	(*RenewCertificateResponse)(nil),     // 4: certpilot.provider.v1.RenewCertificateResponse
	(*RevokeCertificateRequest)(nil),     // 5: certpilot.provider.v1.RevokeCertificateRequest
	(*RevokeCertificateResponse)(nil),    // 6: certpilot.provider.v1.RevokeCertificateResponse
	(*GetCertificateStatusRequest)(nil),  // 7: certpilot.provider.v1.GetCertificateStatusRequest
	(*GetCertificateStatusResponse)(nil), // 8: certpilot.provider.v1.GetCertificateStatusResponse
	(*RenewalWindow)(nil),                // 9: certpilot.provider.v1.RenewalWindow
	(*GetCAInfoRequest)(nil),             // 10: certpilot.provider.v1.GetCAInfoRequest
	(*GetCAInfoResponse)(nil),            // 11: certpilot.provider.v1.GetCAInfoResponse
	(*GetCapabilitiesRequest)(nil),       // 12: certpilot.provider.v1.GetCapabilitiesRequest
	(*GetCapabilitiesResponse)(nil),      // 13: certpilot.provider.v1.GetCapabilitiesResponse
	(*HealthCheckRequest)(nil),           // 14: certpilot.provider.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),          // 15: certpilot.provider.v1.HealthCheckResponse
	(*ValidateConfigRequest)(nil),        // 16: certpilot.provider.v1.ValidateConfigRequest
	(*ValidateConfigResponse)(nil),       // 17: certpilot.provider.v1.ValidateConfigResponse
	(*v1.CertificateInfo)(nil),           // 18: certpilot.common.v1.CertificateInfo
	(*timestamppb.Timestamp)(nil),        // 19: google.protobuf.Timestamp
	(*v1.CAAuthorityInfo)(nil),           // 20: certpilot.common.v1.CAAuthorityInfo
	(*v1.ProviderCapabilities)(nil),      // 21: certpilot.common.v1.ProviderCapabilities
	(v1.HealthStatus)(0),                 // 22: certpilot.common.v1.HealthStatus
}
var file_provider_v1_provider_proto_depIdxs = []int32{
	18, // 0: certpilot.provider.v1.IssueCertificateResponse.certificate:type_name -> certpilot.common.v1.CertificateInfo
	18, // 1: certpilot.provider.v1.RenewCertificateResponse.certificate:type_name -> certpilot.common.v1.CertificateInfo
	0,  // 2: certpilot.provider.v1.GetCertificateStatusResponse.status:type_name -> certpilot.provider.v1.CertStatus
	19, // 3: certpilot.provider.v1.GetCertificateStatusResponse.expires_at:type_name -> google.protobuf.Timestamp
	9,  // 4: certpilot.provider.v1.GetCertificateStatusResponse.renewal_window:type_name -> certpilot.provider.v1.RenewalWindow
	19, // 5: certpilot.provider.v1.RenewalWindow.start:type_name -> google.protobuf.Timestamp
	19, // 6: certpilot.provider.v1.RenewalWindow.end:type_name -> google.protobuf.Timestamp
	20, // 7: certpilot.provider.v1.GetCAInfoResponse.ca_chain:type_name -> certpilot.common.v1.CAAuthorityInfo
	21, // 8: certpilot.provider.v1.GetCapabilitiesResponse.capabilities:type_name -> certpilot.common.v1.ProviderCapabilities
	22, // 9: certpilot.provider.v1.HealthCheckResponse.status:type_name -> certpilot.common.v1.HealthStatus
	19, // 10: certpilot.provider.v1.HealthCheckResponse.checked_at:type_name -> google.protobuf.Timestamp
	1,  // 11: certpilot.provider.v1.CertificateProviderService.IssueCertificate:input_type -> certpilot.provider.v1.IssueCertificateRequest
	3,  // 12: certpilot.provider.v1.CertificateProviderService.RenewCertificate:input_type -> certpilot.provider.v1.RenewCertificateRequest
	5,  // 13: certpilot.provider.v1.CertificateProviderService.RevokeCertificate:input_type -> certpilot.provider.v1.RevokeCertificateRequest
	7,  // 14: certpilot.provider.v1.CertificateProviderService.GetCertificateStatus:input_type -> certpilot.provider.v1.GetCertificateStatusRequest
	10, // 15: certpilot.provider.v1.CertificateProviderService.GetCAInfo:input_type -> certpilot.provider.v1.GetCAInfoRequest
	12, // 16: certpilot.provider.v1.CertificateProviderService.GetCapabilities:input_type -> certpilot.provider.v1.GetCapabilitiesRequest
	14, // 17: certpilot.provider.v1.CertificateProviderService.HealthCheck:input_type -> certpilot.provider.v1.HealthCheckRequest
	16, // 18: certpilot.provider.v1.CertificateProviderService.ValidateConfig:input_type -> certpilot.provider.v1.ValidateConfigRequest
	2,  // 19: certpilot.provider.v1.CertificateProviderService.IssueCertificate:output_type -> certpilot.provider.v1.IssueCertificateResponse
	4,  // 20: certpilot.provider.v1.CertificateProviderService.RenewCertificate:output_type -> certpilot.provider.v1.RenewCertificateResponse
	6,  // 21: certpilot.provider.v1.CertificateProviderService.RevokeCertificate:output_type -> certpilot.provider.v1.RevokeCertificateResponse
	8,  // 22: certpilot.provider.v1.CertificateProviderService.GetCertificateStatus:output_type -> certpilot.provider.v1.GetCertificateStatusResponse
	11, // 23: certpilot.provider.v1.CertificateProviderService.GetCAInfo:output_type -> certpilot.provider.v1.GetCAInfoResponse
	13, // 24: certpilot.provider.v1.CertificateProviderService.GetCapabilities:output_type -> certpilot.provider.v1.GetCapabilitiesResponse
	15, // 25: certpilot.provider.v1.CertificateProviderService.HealthCheck:output_type -> certpilot.provider.v1.HealthCheckResponse
	17, // 26: certpilot.provider.v1.CertificateProviderService.ValidateConfig:output_type -> certpilot.provider.v1.ValidateConfigResponse
	19, // [19:27] is the sub-list for method output_type
	11, // [11:19] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_provider_v1_provider_proto_init() }
func file_provider_v1_provider_proto_init() {
	if File_provider_v1_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_provider_v1_provider_proto_rawDesc), len(file_provider_v1_provider_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_provider_v1_provider_proto_goTypes,
		DependencyIndexes: file_provider_v1_provider_proto_depIdxs,
		EnumInfos:         file_provider_v1_provider_proto_enumTypes,
		MessageInfos:      file_provider_v1_provider_proto_msgTypes,
	}.Build()
	File_provider_v1_provider_proto = out.File
	file_provider_v1_provider_proto_goTypes = nil
	file_provider_v1_provider_proto_depIdxs = nil
}
