// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: provider/v1/provider.proto

package providerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CertificateProviderService_IssueCertificate_FullMethodName     = "/certpilot.provider.v1.CertificateProviderService/IssueCertificate"
	CertificateProviderService_RenewCertificate_FullMethodName     = "/certpilot.provider.v1.CertificateProviderService/RenewCertificate"
	CertificateProviderService_RevokeCertificate_FullMethodName    = "/certpilot.provider.v1.CertificateProviderService/RevokeCertificate"
	CertificateProviderService_GetCertificateStatus_FullMethodName = "/certpilot.provider.v1.CertificateProviderService/GetCertificateStatus"
	CertificateProviderService_GetCAInfo_FullMethodName            = "/certpilot.provider.v1.CertificateProviderService/GetCAInfo"
	CertificateProviderService_GetCapabilities_FullMethodName      = "/certpilot.provider.v1.CertificateProviderService/GetCapabilities"
	CertificateProviderService_HealthCheck_FullMethodName          = "/certpilot.provider.v1.CertificateProviderService/HealthCheck"
	CertificateProviderService_ValidateConfig_FullMethodName       = "/certpilot.provider.v1.CertificateProviderService/ValidateConfig"
)

// CertificateProviderServiceClient is the client API for CertificateProviderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CertificateProviderService is the gRPC contract that every gateway plugin
// must implement. The CertPilot core communicates with gateways exclusively
// through this interface.
type CertificateProviderServiceClient interface {
	// IssueCertificate requests a new certificate from the CA.
	IssueCertificate(ctx context.Context, in *IssueCertificateRequest, opts ...grpc.CallOption) (*IssueCertificateResponse, error)
	// RenewCertificate renews an existing certificate.
	RenewCertificate(ctx context.Context, in *RenewCertificateRequest, opts ...grpc.CallOption) (*RenewCertificateResponse, error)
	// RevokeCertificate revokes a previously issued certificate.
	RevokeCertificate(ctx context.Context, in *RevokeCertificateRequest, opts ...grpc.CallOption) (*RevokeCertificateResponse, error)
	// GetCertificateStatus checks the current status of a certificate.
	GetCertificateStatus(ctx context.Context, in *GetCertificateStatusRequest, opts ...grpc.CallOption) (*GetCertificateStatusResponse, error)
	// GetCAInfo returns information about the issuing CA (if supported).
	GetCAInfo(ctx context.Context, in *GetCAInfoRequest, opts ...grpc.CallOption) (*GetCAInfoResponse, error)
	// GetCapabilities returns what this gateway supports.
	GetCapabilities(ctx context.Context, in *GetCapabilitiesRequest, opts ...grpc.CallOption) (*GetCapabilitiesResponse, error)
	// HealthCheck verifies the gateway is operational and can reach its CA.
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// ValidateConfig checks if a given configuration is valid for this gateway.
	ValidateConfig(ctx context.Context, in *ValidateConfigRequest, opts ...grpc.CallOption) (*ValidateConfigResponse, error)
}

type certificateProviderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCertificateProviderServiceClient(cc grpc.ClientConnInterface) CertificateProviderServiceClient {
	return &certificateProviderServiceClient{cc}
}

func (c *certificateProviderServiceClient) IssueCertificate(ctx context.Context, in *IssueCertificateRequest, opts ...grpc.CallOption) (*IssueCertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueCertificateResponse)
	err := c.cc.Invoke(ctx, CertificateProviderService_IssueCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certificateProviderServiceClient) RenewCertificate(ctx context.Context, in *RenewCertificateRequest, opts ...grpc.CallOption) (*RenewCertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenewCertificateResponse)
	err := c.cc.Invoke(ctx, CertificateProviderService_RenewCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certificateProviderServiceClient) RevokeCertificate(ctx context.Context, in *RevokeCertificateRequest, opts ...grpc.CallOption) (*RevokeCertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeCertificateResponse)
	err := c.cc.Invoke(ctx, CertificateProviderService_RevokeCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certificateProviderServiceClient) GetCertificateStatus(ctx context.Context, in *GetCertificateStatusRequest, opts ...grpc.CallOption) (*GetCertificateStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCertificateStatusResponse)
	err := c.cc.Invoke(ctx, CertificateProviderService_GetCertificateStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certificateProviderServiceClient) GetCAInfo(ctx context.Context, in *GetCAInfoRequest, opts ...grpc.CallOption) (*GetCAInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCAInfoResponse)
	err := c.cc.Invoke(ctx, CertificateProviderService_GetCAInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certificateProviderServiceClient) GetCapabilities(ctx context.Context, in *GetCapabilitiesRequest, opts ...grpc.CallOption) (*GetCapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCapabilitiesResponse)
	err := c.cc.Invoke(ctx, CertificateProviderService_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certificateProviderServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, CertificateProviderService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certificateProviderServiceClient) ValidateConfig(ctx context.Context, in *ValidateConfigRequest, opts ...grpc.CallOption) (*ValidateConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateConfigResponse)
	err := c.cc.Invoke(ctx, CertificateProviderService_ValidateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CertificateProviderServiceServer is the server API for CertificateProviderService service.
// All implementations must embed UnimplementedCertificateProviderServiceServer
// for forward compatibility.
//
// CertificateProviderService is the gRPC contract that every gateway plugin
// must implement. The CertPilot core communicates with gateways exclusively
// through this interface.
type CertificateProviderServiceServer interface {
	// IssueCertificate requests a new certificate from the CA.
	IssueCertificate(context.Context, *IssueCertificateRequest) (*IssueCertificateResponse, error)
	// RenewCertificate renews an existing certificate.
	RenewCertificate(context.Context, *RenewCertificateRequest) (*RenewCertificateResponse, error)
	// RevokeCertificate revokes a previously issued certificate.
	RevokeCertificate(context.Context, *RevokeCertificateRequest) (*RevokeCertificateResponse, error)
	// GetCertificateStatus checks the current status of a certificate.
	GetCertificateStatus(context.Context, *GetCertificateStatusRequest) (*GetCertificateStatusResponse, error)
	// GetCAInfo returns information about the issuing CA (if supported).
	GetCAInfo(context.Context, *GetCAInfoRequest) (*GetCAInfoResponse, error)
	// GetCapabilities returns what this gateway supports.
	GetCapabilities(context.Context, *GetCapabilitiesRequest) (*GetCapabilitiesResponse, error)
	// HealthCheck verifies the gateway is operational and can reach its CA.
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// ValidateConfig checks if a given configuration is valid for this gateway.
	ValidateConfig(context.Context, *ValidateConfigRequest) (*ValidateConfigResponse, error)
	mustEmbedUnimplementedCertificateProviderServiceServer()
}

// UnimplementedCertificateProviderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCertificateProviderServiceServer struct{}

func (UnimplementedCertificateProviderServiceServer) IssueCertificate(context.Context, *IssueCertificateRequest) (*IssueCertificateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IssueCertificate not implemented")
}
func (UnimplementedCertificateProviderServiceServer) RenewCertificate(context.Context, *RenewCertificateRequest) (*RenewCertificateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenewCertificate not implemented")
}
func (UnimplementedCertificateProviderServiceServer) RevokeCertificate(context.Context, *RevokeCertificateRequest) (*RevokeCertificateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeCertificate not implemented")
}
func (UnimplementedCertificateProviderServiceServer) GetCertificateStatus(context.Context, *GetCertificateStatusRequest) (*GetCertificateStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCertificateStatus not implemented")
}
func (UnimplementedCertificateProviderServiceServer) GetCAInfo(context.Context, *GetCAInfoRequest) (*GetCAInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCAInfo not implemented")
}
func (UnimplementedCertificateProviderServiceServer) GetCapabilities(context.Context, *GetCapabilitiesRequest) (*GetCapabilitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedCertificateProviderServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedCertificateProviderServiceServer) ValidateConfig(context.Context, *ValidateConfigRequest) (*ValidateConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateConfig not implemented")
}
func (UnimplementedCertificateProviderServiceServer) mustEmbedUnimplementedCertificateProviderServiceServer() {
}
func (UnimplementedCertificateProviderServiceServer) testEmbeddedByValue() {}

// UnsafeCertificateProviderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CertificateProviderServiceServer will
// result in compilation errors.
type UnsafeCertificateProviderServiceServer interface {
	mustEmbedUnimplementedCertificateProviderServiceServer()
}

func RegisterCertificateProviderServiceServer(s grpc.ServiceRegistrar, srv CertificateProviderServiceServer) {
	// If the following call panics, it indicates UnimplementedCertificateProviderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CertificateProviderService_ServiceDesc, srv)
}

func _CertificateProviderService_IssueCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateProviderServiceServer).IssueCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CertificateProviderService_IssueCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateProviderServiceServer).IssueCertificate(ctx, req.(*IssueCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertificateProviderService_RenewCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateProviderServiceServer).RenewCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CertificateProviderService_RenewCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateProviderServiceServer).RenewCertificate(ctx, req.(*RenewCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertificateProviderService_RevokeCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateProviderServiceServer).RevokeCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CertificateProviderService_RevokeCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateProviderServiceServer).RevokeCertificate(ctx, req.(*RevokeCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertificateProviderService_GetCertificateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCertificateStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateProviderServiceServer).GetCertificateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CertificateProviderService_GetCertificateStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateProviderServiceServer).GetCertificateStatus(ctx, req.(*GetCertificateStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertificateProviderService_GetCAInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCAInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateProviderServiceServer).GetCAInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CertificateProviderService_GetCAInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateProviderServiceServer).GetCAInfo(ctx, req.(*GetCAInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertificateProviderService_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateProviderServiceServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CertificateProviderService_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateProviderServiceServer).GetCapabilities(ctx, req.(*GetCapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertificateProviderService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateProviderServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CertificateProviderService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateProviderServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertificateProviderService_ValidateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateProviderServiceServer).ValidateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CertificateProviderService_ValidateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateProviderServiceServer).ValidateConfig(ctx, req.(*ValidateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CertificateProviderService_ServiceDesc is the grpc.ServiceDesc for CertificateProviderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CertificateProviderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "certpilot.provider.v1.CertificateProviderService",
	HandlerType: (*CertificateProviderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IssueCertificate",
			Handler:    _CertificateProviderService_IssueCertificate_Handler,
		},
		{
			MethodName: "RenewCertificate",
			Handler:    _CertificateProviderService_RenewCertificate_Handler,
		},
		{
			MethodName: "RevokeCertificate",
			Handler:    _CertificateProviderService_RevokeCertificate_Handler,
		},
		{
			MethodName: "GetCertificateStatus",
			Handler:    _CertificateProviderService_GetCertificateStatus_Handler,
		},
		{
			MethodName: "GetCAInfo",
			Handler:    _CertificateProviderService_GetCAInfo_Handler,
		},
		{
			MethodName: "GetCapabilities",
			Handler:    _CertificateProviderService_GetCapabilities_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _CertificateProviderService_HealthCheck_Handler,
		},
		{
			MethodName: "ValidateConfig",
			Handler:    _CertificateProviderService_ValidateConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "provider/v1/provider.proto",
}
