package vault

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"strings"
)

// issuedCert is what Vault returns from sign or issue.
type issuedCert struct {
	Certificate string   `json:"certificate"`
	IssuingCA   string   `json:"issuing_ca"`
	CAChain     []string `json:"ca_chain"`
	// SerialNumber is colon-separated hexadecimal, which is the form Vault
	// accepts back for revocation and lookup. It is not the form X.509
	// tooling prints, and the two have to be converted rather than compared.
	SerialNumber string `json:"serial_number"`
	Expiration   int64  `json:"expiration"`
	// PrivateKey is present only from the issue endpoint, where Vault
	// generated the key because nobody supplied a CSR.
	PrivateKey     string `json:"private_key"`
	PrivateKeyType string `json:"private_key_type"`
}

// storedCert is a certificate Vault kept a copy of.
type storedCert struct {
	Certificate    string `json:"certificate"`
	RevocationTime int64  `json:"revocation_time"`
}

// issuerData is one issuer of a PKI mount.
type issuerData struct {
	Certificate   string   `json:"certificate"`
	CAChain       []string `json:"ca_chain"`
	IssuerName    string   `json:"issuer_name"`
	IssuerID      string   `json:"issuer_id"`
	CRLDistPoints []string `json:"crl_distribution_points"`
	OCSPServers   []string `json:"ocsp_servers"`
}

// roleData is the part of a PKI role that changes what an operator gets.
//
// Every field here can silently override what CertPilot asked for, which is
// why they are read at configuration time and reported back rather than
// discovered from a certificate that came out different.
type roleData struct {
	TTL              flexInt  `json:"ttl"`
	MaxTTL           flexInt  `json:"max_ttl"`
	KeyType          string   `json:"key_type"`
	KeyBits          flexInt  `json:"key_bits"`
	UseCSRCommonName bool     `json:"use_csr_common_name"`
	UseCSRSANs       bool     `json:"use_csr_sans"`
	AllowedDomains   []string `json:"allowed_domains"`
	AllowSubdomains  bool     `json:"allow_subdomains"`
	AllowAnyName     bool     `json:"allow_any_name"`
	AllowBareDomains bool     `json:"allow_bare_domains"`
	// NoStore means Vault does not keep a copy of what it signs. Certificates
	// from such a role cannot be revoked by serial and cannot be looked up,
	// and the only moment anyone finds out is the moment they need to.
	NoStore bool `json:"no_store"`
}

// flexInt reads a number Vault may send as a JSON number or a string.
//
// Both appear across versions and across fields on the same response, so
// choosing one and being wrong means a configuration read that fails on a
// Vault that is working perfectly.
type flexInt int64

func (f *flexInt) UnmarshalJSON(raw []byte) error {
	text := strings.Trim(string(raw), `"`)
	if text == "" || text == "null" {
		return nil
	}
	value, err := strconv.ParseInt(text, 10, 64)
	if err != nil {
		return nil
	}
	*f = flexInt(value)
	return nil
}

// healthData is Vault's own account of itself.
type healthData struct {
	Initialized        bool   `json:"initialized"`
	Sealed             bool   `json:"sealed"`
	Standby            bool   `json:"standby"`
	PerformanceStandby bool   `json:"performance_standby"`
	Version            string `json:"version"`
	ClusterName        string `json:"cluster_name"`
}

// sign asks Vault to sign a CSR under the configured role.
//
// This is the path that matters: the key was generated by whoever made the
// CSR — on the host that will serve the certificate, when the request came
// from an agent — and neither Vault nor CertPilot ever holds it.
//
// The role signs, not sign-verbatim. sign-verbatim honours the extensions in
// the CSR, which means the CSR decides its own key usage and, on a mount whose
// role would otherwise have refused, its own basic constraints. The role
// exists to constrain; going around it is going around the reason it is there.
func (p *Provider) sign(ctx context.Context, cfg *Config, csrPEM string, domains []string, ttl string) (*issuedCert, []string, error) {
	body := map[string]any{"csr": csrPEM, "format": "pem"}
	applyNames(body, domains)
	if ttl != "" {
		body["ttl"] = ttl
	}

	var out issuedCert
	warnings, err := p.call(ctx, cfg, http.MethodPost, cfg.issuancePath("sign"), body, &out)
	if err != nil {
		return nil, warnings, err
	}
	return &out, warnings, nil
}

// issue asks Vault to generate a key and sign it.
//
// Used when the core supplied no CSR. The key is generated inside Vault and
// travels back over this connection, which is why the CSR path is preferred
// wherever the caller can produce one.
func (p *Provider) issue(ctx context.Context, cfg *Config, domains []string, ttl string) (*issuedCert, []string, error) {
	body := map[string]any{"format": "pem"}
	applyNames(body, domains)
	if ttl != "" {
		body["ttl"] = ttl
	}

	var out issuedCert
	warnings, err := p.call(ctx, cfg, http.MethodPost, cfg.issuancePath("issue"), body, &out)
	if err != nil {
		return nil, warnings, err
	}
	return &out, warnings, nil
}

// applyNames puts the requested names on a request.
//
// The common name is not repeated in alt_names: Vault adds it to the SANs
// itself, and sending it twice produces a certificate with a duplicated SAN
// entry that some validators complain about and every operator has to explain.
func applyNames(body map[string]any, domains []string) {
	if len(domains) == 0 {
		return
	}
	body["common_name"] = domains[0]
	if rest := domains[1:]; len(rest) > 0 {
		body["alt_names"] = strings.Join(rest, ",")
	}
}

// revoke asks Vault to revoke a certificate.
//
// Preferring the certificate over the serial is not a style choice: Vault's
// serial format is colon-separated hexadecimal, X.509 tooling prints the same
// number several other ways, and a serial that has been through one conversion
// too many revokes nothing while reporting success at the HTTP layer.
func (p *Provider) revoke(ctx context.Context, cfg *Config, certPEM, serial string) (int64, error) {
	body := map[string]any{}
	switch {
	case strings.TrimSpace(certPEM) != "":
		body["certificate"] = certPEM
	case strings.TrimSpace(serial) != "":
		body["serial_number"] = vaultSerial(serial)
	default:
		return 0, fmt.Errorf("revocation needs either the certificate or its serial number")
	}

	var out struct {
		RevocationTime int64 `json:"revocation_time"`
	}
	if _, err := p.call(ctx, cfg, http.MethodPost, cfg.pkiPath("revoke"), body, &out); err != nil {
		return 0, err
	}
	return out.RevocationTime, nil
}

// readCert fetches a certificate Vault stored, and when it was revoked.
func (p *Provider) readCert(ctx context.Context, cfg *Config, serial string) (*storedCert, error) {
	var out storedCert
	_, err := p.call(ctx, cfg, http.MethodGet,
		cfg.pkiPath("cert", url.PathEscape(vaultSerial(serial))), nil, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// listIssuers names every issuer on the mount.
func (p *Provider) listIssuers(ctx context.Context, cfg *Config) ([]string, error) {
	var out struct {
		Keys []string `json:"keys"`
	}
	// The LIST verb over plain HTTP, which is how every client that is not
	// Vault's own does it.
	_, err := p.call(ctx, cfg, http.MethodGet, cfg.pkiPath("issuers")+"?list=true", nil, &out)
	if err != nil {
		return nil, err
	}
	return out.Keys, nil
}

// readIssuer fetches one issuer's certificate and chain.
func (p *Provider) readIssuer(ctx context.Context, cfg *Config, ref string) (*issuerData, error) {
	var out issuerData
	_, err := p.call(ctx, cfg, http.MethodGet,
		cfg.pkiPath("issuer", url.PathEscape(ref), "json"), nil, &out)
	if err != nil {
		return nil, err
	}
	if out.IssuerID == "" {
		out.IssuerID = ref
	}
	return &out, nil
}

// readDefaultCA falls back to the pre-multi-issuer endpoint.
//
// Mounts created before Vault 1.11, and tokens whose policy covers the mount
// but not its issuer paths, both answer here and nowhere else.
func (p *Provider) readDefaultCA(ctx context.Context, cfg *Config) (*issuerData, error) {
	var out struct {
		Certificate string   `json:"certificate"`
		CAChain     []string `json:"ca_chain"`
	}
	if _, err := p.call(ctx, cfg, http.MethodGet, cfg.pkiPath("cert", "ca"), nil, &out); err != nil {
		return nil, err
	}
	if strings.TrimSpace(out.Certificate) == "" {
		return nil, fmt.Errorf("the %s mount has no CA certificate; it has been mounted but never given one", cfg.Mount)
	}
	return &issuerData{Certificate: out.Certificate, CAChain: out.CAChain, IssuerID: "default"}, nil
}

// readRole reads the role, or reports why it could not.
//
// Callers treat failure as "unknown" rather than as an error: reading a role
// needs a policy that grants it, and a token scoped tightly enough to issue and
// nothing else is a well-configured token, not a broken one.
func (p *Provider) readRole(ctx context.Context, cfg *Config) (*roleData, error) {
	var out roleData
	_, err := p.call(ctx, cfg, http.MethodGet,
		cfg.pkiPath("roles", url.PathEscape(cfg.Role)), nil, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// mountURLs is where a mount tells clients to look for its certificates, CRL
// and OCSP responder.
//
// These are mount-wide settings rather than properties of an issuer, and they
// are not in an issuer's certificate unless it was signed after they were set
// — which, for the CA that was created when the mount was created, it never
// was.
type mountURLs struct {
	IssuingCertificates   []string `json:"issuing_certificates"`
	CRLDistributionPoints []string `json:"crl_distribution_points"`
	OCSPServers           []string `json:"ocsp_servers"`
}

// readURLs reads the mount's URL configuration, or reports nothing.
//
// Absence is ordinary: an unconfigured mount publishes no URLs, and a
// tightly scoped token may not be allowed to read the setting.
func (p *Provider) readURLs(ctx context.Context, cfg *Config) *mountURLs {
	var out mountURLs
	if _, err := p.call(ctx, cfg, http.MethodGet, cfg.pkiPath("config", "urls"), nil, &out); err != nil {
		return &mountURLs{}
	}
	return &out
}

// health reads sys/health, translating the status codes Vault uses to mean
// things other than failure.
func (p *Provider) health(ctx context.Context, cfg *Config) (*healthData, error) {
	// Unauthenticated on purpose: sys/health answers without a token, so a
	// reachability check does not depend on a credential being valid, and the
	// two failures stay distinguishable.
	var out healthData
	err := p.requestTop(ctx, cfg, http.MethodGet, "/v1/sys/health", "", &out)
	if err == nil {
		return &out, nil
	}

	ve, ok := asAPIError(err)
	if !ok {
		return nil, err
	}
	// Vault answers this endpoint with a status per state, and several of the
	// non-200s describe a node that is working. A gateway that treated
	// 429 as rate limiting would back off from a healthy standby.
	switch ve.Status {
	case http.StatusTooManyRequests:
		return &healthData{Initialized: true, Standby: true}, nil
	case 473:
		return &healthData{Initialized: true, Standby: true, PerformanceStandby: true}, nil
	case http.StatusServiceUnavailable:
		return &healthData{Initialized: true, Sealed: true}, nil
	case http.StatusNotImplemented:
		return &healthData{Initialized: false}, nil
	default:
		return nil, err
	}
}

// vaultSerial converts a serial number into the colon-separated hexadecimal
// Vault uses.
//
// X.509 tooling prints serials as plain hex, sometimes with a leading zero
// dropped, sometimes as decimal. Vault derives its form from the same big
// integer, so padding to whole bytes and grouping in pairs reconstructs it
// exactly. An odd-length string that is passed through unpadded produces a
// serial Vault has never heard of, and a revocation that succeeds at the HTTP
// layer and revokes nothing.
func vaultSerial(serial string) string {
	cleaned := strings.Map(func(r rune) rune {
		switch {
		case r >= '0' && r <= '9', r >= 'a' && r <= 'f':
			return r
		case r >= 'A' && r <= 'F':
			return r + 32
		}
		return -1
	}, serial)
	if cleaned == "" {
		return ""
	}
	if len(cleaned)%2 == 1 {
		cleaned = "0" + cleaned
	}

	var b strings.Builder
	for i := 0; i < len(cleaned); i += 2 {
		if i > 0 {
			b.WriteByte(':')
		}
		b.WriteString(cleaned[i : i+2])
	}
	return b.String()
}

// chainPEM joins a CA chain into one PEM bundle, dropping the leaf's own
// issuer duplicate that Vault includes in both fields.
func chainPEM(cert *issuedCert) string {
	seen := map[string]bool{}
	parts := []string{}
	for _, pemBlock := range cert.CAChain {
		trimmed := strings.TrimSpace(pemBlock)
		if trimmed == "" || seen[trimmed] {
			continue
		}
		seen[trimmed] = true
		parts = append(parts, trimmed)
	}
	if len(parts) == 0 && strings.TrimSpace(cert.IssuingCA) != "" {
		parts = append(parts, strings.TrimSpace(cert.IssuingCA))
	}
	if len(parts) == 0 {
		return ""
	}
	return strings.Join(parts, "\n") + "\n"
}
