// Package selfsigned implements a CertificateProviderService gateway
// that generates self-signed certificates. Used for development and testing.
package selfsigned

import (
	"context"
	"crypto"
	"crypto/rand"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"fmt"
	"log/slog"
	"math/big"
	"time"

	certcrypto "github.com/certpilot/certpilot/pkg/crypto"
	commonv1 "github.com/certpilot/certpilot/pkg/pb/common/v1"
	providerv1 "github.com/certpilot/certpilot/pkg/pb/provider/v1"

	"google.golang.org/protobuf/types/known/timestamppb"
)

// Provider implements the CertificateProviderService for self-signed certificates.
type Provider struct {
	providerv1.UnimplementedCertificateProviderServiceServer
	startedAt time.Time
}

// NewProvider creates a new self-signed provider.
func NewProvider() *Provider {
	return &Provider{
		startedAt: time.Now(),
	}
}

// IssueCertificate produces a certificate for development and testing.
//
// Two paths, and the difference is where the private key was born.
//
// With a CSR, the key was generated by whoever is asking — on the host that
// will serve the certificate, which is the whole point of the agent — and this
// gateway signs the request with a small CA it creates for the process. It
// never sees the private key and returns none.
//
// Without one, it does what it always did: generates a key here and returns it
// over gRPC. Convenient, mTLS-protected, and still the weaker pattern, because
// the key exists somewhere it did not need to.
func (p *Provider) IssueCertificate(ctx context.Context, req *providerv1.IssueCertificateRequest) (*providerv1.IssueCertificateResponse, error) {
	if len(req.CsrPem) > 0 {
		return issueFromCSR(req)
	}

	slog.Info("issuing self-signed certificate", "domains", req.Domains)

	// Determine key type and size
	keyType := certcrypto.KeyTypeRSA
	keySize := 2048
	if req.KeyType != "" {
		var err error
		keyType, err = certcrypto.ParseKeyType(req.KeyType)
		if err != nil {
			return nil, fmt.Errorf("invalid key type: %w", err)
		}
	}
	if req.KeySize > 0 {
		keySize = int(req.KeySize)
	}

	// Generate key pair
	privateKey, err := certcrypto.GenerateKeyPair(keyType, keySize)
	if err != nil {
		return nil, fmt.Errorf("failed to generate key pair: %w", err)
	}

	// Determine validity
	validityDays := 365
	if req.ValidityDays > 0 {
		validityDays = int(req.ValidityDays)
	}

	// Determine common name
	commonName := "localhost"
	if len(req.Domains) > 0 {
		commonName = req.Domains[0]
	}

	// Generate serial number
	serialNumber, err := rand.Int(rand.Reader, new(big.Int).Lsh(big.NewInt(1), 128))
	if err != nil {
		return nil, fmt.Errorf("failed to generate serial number: %w", err)
	}

	now := time.Now()
	template := &x509.Certificate{
		SerialNumber: serialNumber,
		Subject: pkix.Name{
			CommonName:   commonName,
			Organization: []string{"CertPilot Self-Signed"},
		},
		DNSNames:              req.Domains,
		NotBefore:             now,
		NotAfter:              now.Add(time.Duration(validityDays) * 24 * time.Hour),
		KeyUsage:              x509.KeyUsageDigitalSignature | x509.KeyUsageKeyEncipherment | x509.KeyUsageCertSign,
		ExtKeyUsage:           []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth, x509.ExtKeyUsageClientAuth},
		BasicConstraintsValid: true,
		IsCA:                  true,
	}

	// Self-sign the certificate
	pubKey, err := extractPublicKey(privateKey)
	if err != nil {
		return nil, fmt.Errorf("failed to extract public key: %w", err)
	}
	certDER, err := x509.CreateCertificate(rand.Reader, template, template, pubKey, privateKey)
	if err != nil {
		return nil, fmt.Errorf("failed to create certificate: %w", err)
	}

	certPEM := pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: certDER})
	keyPEM, err := certcrypto.EncodePrivateKeyPEM(privateKey)
	if err != nil {
		return nil, fmt.Errorf("failed to encode private key: %w", err)
	}

	slog.Info("self-signed certificate issued",
		"cn", commonName,
		"serial", serialNumber.Text(16),
		"expires", template.NotAfter.Format(time.RFC3339),
	)

	return &providerv1.IssueCertificateResponse{
		Certificate: &commonv1.CertificateInfo{
			CommonName:     commonName,
			Sans:           req.Domains,
			SerialNumber:   serialNumber.Text(16),
			IssuerDn:       template.Subject.String(),
			SubjectDn:      template.Subject.String(),
			NotBefore:      timestamppb.New(template.NotBefore),
			NotAfter:       timestamppb.New(template.NotAfter),
			KeyType:        string(keyType),
			KeySize:        int32(keySize),
			CertificatePem: certPEM,
			PrivateKeyPem:  keyPEM,
		},
		ProviderCertificateId: serialNumber.Text(16),
	}, nil
}

// RenewCertificate generates a new self-signed certificate (same as issue for self-signed).
func (p *Provider) RenewCertificate(ctx context.Context, req *providerv1.RenewCertificateRequest) (*providerv1.RenewCertificateResponse, error) {
	slog.Info("renewing self-signed certificate", "domains", req.Domains)

	issueResp, err := p.IssueCertificate(ctx, &providerv1.IssueCertificateRequest{
		// The CSR is carried through, so a renewal for a key held on a host
		// stays a renewal for a key held on that host.
		CsrPem:  req.CsrPem,
		Domains: req.Domains,
		KeyType: req.KeyType,
		KeySize: req.KeySize,
	})
	if err != nil {
		return nil, err
	}

	return &providerv1.RenewCertificateResponse{
		Certificate:           issueResp.Certificate,
		ProviderCertificateId: issueResp.ProviderCertificateId,
	}, nil
}

// RevokeCertificate is a no-op for self-signed certificates.
func (p *Provider) RevokeCertificate(ctx context.Context, req *providerv1.RevokeCertificateRequest) (*providerv1.RevokeCertificateResponse, error) {
	slog.Info("revoking self-signed certificate (no-op)", "id", req.ProviderCertificateId)
	return &providerv1.RevokeCertificateResponse{
		Success: true,
		Message: "self-signed certificate marked as revoked (no CRL)",
	}, nil
}

// GetCertificateStatus returns the status (always valid for self-signed).
func (p *Provider) GetCertificateStatus(ctx context.Context, req *providerv1.GetCertificateStatusRequest) (*providerv1.GetCertificateStatusResponse, error) {
	return &providerv1.GetCertificateStatusResponse{
		Status:  providerv1.CertStatus_CERT_STATUS_VALID,
		Message: "self-signed certificate",
	}, nil
}

// GetCAInfo returns empty (self-signed has no CA chain).
func (p *Provider) GetCAInfo(ctx context.Context, req *providerv1.GetCAInfoRequest) (*providerv1.GetCAInfoResponse, error) {
	return &providerv1.GetCAInfoResponse{
		CaChain: []*commonv1.CAAuthorityInfo{},
	}, nil
}

// GetCapabilities returns what this gateway supports.
func (p *Provider) GetCapabilities(ctx context.Context, req *providerv1.GetCapabilitiesRequest) (*providerv1.GetCapabilitiesResponse, error) {
	return &providerv1.GetCapabilitiesResponse{
		Capabilities: &commonv1.ProviderCapabilities{
			ProviderName:        "selfsigned",
			ProviderVersion:     "1.0.0",
			ProviderType:        "selfsigned",
			SupportsWildcard:    true,
			SupportsMultiDomain: true,
			SupportedKeyTypes:   []string{"RSA", "ECDSA", "Ed25519"},
			SupportedChallenges: []string{},
			ValidationLevels:    []string{"DV"},
			SupportsRevocation:  false,
			SupportsCaInfo:      false,
			Description:         "Self-signed certificate gateway for development and testing",
		},
	}, nil
}

// HealthCheck verifies the gateway is operational.
func (p *Provider) HealthCheck(ctx context.Context, req *providerv1.HealthCheckRequest) (*providerv1.HealthCheckResponse, error) {
	return &providerv1.HealthCheckResponse{
		Status:    commonv1.HealthStatus_HEALTH_STATUS_HEALTHY,
		Message:   fmt.Sprintf("self-signed gateway running since %s", p.startedAt.Format(time.RFC3339)),
		LatencyMs: 0,
		CheckedAt: timestamppb.Now(),
	}, nil
}

// ValidateConfig validates configuration (always valid for self-signed).
func (p *Provider) ValidateConfig(ctx context.Context, req *providerv1.ValidateConfigRequest) (*providerv1.ValidateConfigResponse, error) {
	return &providerv1.ValidateConfigResponse{
		Valid: true,
	}, nil
}

// extractPublicKey extracts the public key from a private key using crypto.Signer.
func extractPublicKey(priv interface{}) (interface{}, error) {
	if signer, ok := priv.(interface{ Public() crypto.PublicKey }); ok {
		return signer.Public(), nil
	}
	return nil, fmt.Errorf("private key does not implement crypto.Signer")
}
